description: "Large config for shifting tasks within Edge-Fog-Cloud computing"
algo:
  threshold_comp_euclidean_dist: 10
  threshold_rtt: 90
  threshold_penalty_factor: -6
  epoch: 3200 
  pop_size: 20
dag:
  file_path: "docs/dag_large/dag_model.json"