description: "Medium config for shifting tasks from Cloud to Edge"
algo:
  threshold_comp_euclidean_dist: 10
  threshold_rtt: 90
  epoch: 1000 
  pop_size: 50
dag:
  file_path: "docs/dag_medium/dag_model.json"