description: "Large config for shifting tasks from Cloud to Edge"
algo:
  threshold_comp_euclidean_dist: 10
  threshold_rtt: 90
  epoch: 1000 
  pop_size: 100
dag:
  file_path: "docs/dag_large/dag_model.json"